using System.CodeDom.Compiler;
using System.IO;

namespace ParserObjects.CodeGen
{
    internal class TuplesRuleGenerator
    {
        public string GetTuplesDefs()
        {
            var inner = new StringWriter();
            var wr = new IndentedTextWriter(inner);
            wr.WriteLine("// <auto-generated/>");
            wr.WriteLine("using System;");
            wr.WriteLine();
            wr.WriteLine("namespace ParserObjects;");
            wr.WriteLine();
            wr.WriteLine("public static partial class TupleExtensions");
            wr.WriteLine("{");
            wr.Indent++;
            for (int num = 2; num <= 9; num++)
                GenerateMethod(num, wr);

            wr.Indent--;
            wr.WriteLine("}");
            return inner.ToString();
        }

        private void GenerateMethod(int num, IndentedTextWriter wr)
        {
            wr.Write("public static partial IParser<TInput, TOutput> Rule<TInput,");
            wr.TArgsList(num);
            wr.WriteLine(", TOutput>(");
            WriteMethodParameters(num, wr);
            wr.WriteLine(")");
            wr.WriteLine("{");
            wr.Indent++;

            wr.WriteLine("return ParserObjects.Parsers<TInput>.Rule(");
            wr.Indent++;
            WriteTupleArgsList(num, wr);
            wr.Indent--;

            wr.WriteLine(");");
            wr.Indent--;
            wr.WriteLine("}");
            wr.WriteLine();
        }

        private static void WriteMethodParameters(int num, IndentedTextWriter wr)
        {
            wr.Indent++;
            wr.Write("this (");
            for (int i = 1; i <= num; i++)
            {
                wr.Write($"IParser<TInput, T{i}> P{i}");
                if (i < num)
                    wr.Write(", ");
            }

            wr.WriteLine(") parsers,");

            wr.Write("Func<");
            wr.TArgsList(num);
            wr.WriteLine(", TOutput> produce");

            wr.Indent--;
        }

        private static void WriteTupleArgsList(int num, IndentedTextWriter wr)
        {
            wr.WriteLine("parsers.P1,");
            for (int i = 2; i <= num; i++)
                wr.WriteLine($"parsers.P{i},");
            wr.WriteLine("produce");
        }
    }
}
