using System.CodeDom.Compiler;
using System.IO;

namespace ParserObjects.CodeGen
{
    internal class TuplesCombineGenerator
    {
        public string GetTuplesDefs()
        {
            var inner = new StringWriter();
            var wr = new IndentedTextWriter(inner);
            wr.WriteLine("// <auto-generated/>");
            wr.WriteLine("using System;");
            wr.WriteLine("using System.Collections.Generic;");
            wr.WriteLine();
            wr.WriteLine("namespace ParserObjects;");
            wr.WriteLine();
            wr.WriteLine("public static partial class TupleExtensions");
            wr.WriteLine("{");
            wr.Indent++;
            for (int num = 2; num <= 9; num++)
                GenerateCombineMethod(num, wr);

            wr.Indent--;
            wr.WriteLine("}");
            return inner.ToString();
        }

        private void GenerateCombineMethod(int num, IndentedTextWriter wr)
        {
            wr.WriteLine("public static partial IParser<TInput, IReadOnlyList<object>> Combine<TInput>(");
            WriteMethodParameters(num, wr);
            wr.WriteLine();
            wr.WriteLine(")");
            wr.WriteLine("{");
            wr.Indent++;

            wr.WriteLine("return Internal.Parsers.Rule.Create(");
            wr.Indent++;

            WriteTupleToArrayArgument(num, wr);
            wr.WriteLine(",");
            wr.WriteLine("ParserObjects.Internal.Defaults.ObjectInstance,");
            wr.WriteLine("static (_, r) => r");

            wr.Indent--;
            wr.WriteLine(");");
            wr.Indent--;
            wr.WriteLine("}");
            wr.WriteLine();
        }

        private static void WriteTupleToArrayArgument(int num, IndentedTextWriter wr)
        {
            wr.Write("[");
            wr.Write("parsers.P1");
            for (int i = 2; i <= num; i++)
                wr.Write($", parsers.P{i}");
            wr.Write("]");
        }

        private static void WriteMethodParameters(int num, IndentedTextWriter wr)
        {
            wr.Indent++;
            wr.Write("this (");
            for (int i = 1; i <= num; i++)
            {
                wr.Write($"IParser<TInput> P{i}");
                if (i < num)
                    wr.Write(", ");
            }

            wr.Write(") parsers");
            wr.Indent--;
        }
    }
}
